### ISSUE TITLE
2.7.0 breaks all Node versions below 7

### ISSUE THREAD

**Issue by Burstaholic** [AppGeo/wms#11]
This is a significant breaking change and should be a major version bump. Additionally, the `engines` specifier should be added to package.json: https://docs.npmjs.com/files/package.json#engines

Please be careful to appropriately signal when breaking compatibility with the current LTS version of Node.

**Comment by calvinmetcalf** [comment]
ok I can republish monday

**Comment by calvinmetcalf** [comment]
ok republished 2.6.0 as 2.7.1 then published 2.7.0 as 3.0.0 with an engines field, sorry about that, didn't even know other people were using this, glad to hear it!
