### ISSUE TITLE
Adding Email - Breaks Login?

### ISSUE THREAD

**Issue by kmanton** [AppGeo/wms#3]
Email from TNRIS with potential bug. 

"Gayla and I both noticed what may be a bug. This morning, each of us logged into the appliance. The message on the login page said to add our email address to our user profile. So, being the ever obedient people that we are, we complied and we each entered our email address. 

The appliance reset to the login page and prompted us to login again. Upon doing so, our passwords no longer worked. So, we had to hit the "Forgot Password" link to reset our passwords.

We will refrain from adding emails to the system until we know what might be causing this issue."

**Comment by calvinmetcalf** [comment]
I figured it out, will be deploying to wms.appgeo.com shortly

**Comment by calvinmetcalf** [comment]
ok deployed to wms.appgeo.com
